from termcolor import colored
import time

print(colored('Hello, World!', 'yellow'))
print(colored('dowloaded package','white'))
time.sleep(1)
print(colored('extract package','white'))
time.sleep(1)
print(colored('copy file','blue'))
print(colored(' => (10%) - language.pak','white'))
time.sleep(1)
print(colored(' => (20%) - language.pak2','white'))
time.sleep(1)
print(colored(' => (30%) - tree.exe','white'))
time.sleep(1)
print(colored(' => (40%) - user.dll','white'))
time.sleep(1)
print(colored(' => (50%) - user32.dll','white'))
time.sleep(1)
print(colored(' => (60%) - core.dll','white'))
time.sleep(1)
print(colored(' => (70%) - core.exe','white'))
time.sleep(1)
print(colored(' => (80%) - core2.exe','white'))
time.sleep(1)
print(colored(' => (90%) - engine.dll','white'))
time.sleep(1)
print(colored(' => (100%) - engine.exe','white'))
print(colored('success','green'))
time.sleep(0.5)
print(colored('install package','white'))
print(colored(' => erorr install package','red'))
time.sleep(0.5)
print(colored('     => install script not found','red'))
input('Для продолжения нажмите Enter')
